// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: 'postgresql://neondb_owner:npg_TNFhQ2dz1wqs@ep-royal-morning-a1g0n3h9-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'
  },
});
